version: '3.7'
services:
    redis:
      image: redis:latest
      container_name: redis
        #restart: unless-stopped
      restart: always
      hostname: redis
      ports:
        - 6379:6379
      networks:
        - network_comman_service

    postgres:
      container_name: postgres
      hostname: postgres
      restart: always
      image: timescale/timescaledb:1.7.5-pg11
      ports:
        - 5432:5432
      env_file:
        - /opt/fil/.env.prod
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - /var/lib/postgresql/11/main:/var/lib/postgresql/data
      networks:
        - network_comman_service

networks:
  network_comman_service:
    external: true
