input {
       kafka
        {
        bootstrap_servers => "172.18.5.97:9092"
        topics => ["fil_daily_log"]
        client_id => "kafka-ipdns-0"
        group_id => "kafka-ipdns-0"
        auto_offset_reset => "earliest"
        codec => json
	}
}

filter {  
  date {
    match => [ "mytime", "yyyy-MM-dd HH:mm:ss.ZZZZZZ"]
  }
  mutate {
    gsub => [
        "mytime","\ ","T"]
    }
date {
    match => [ "mytime", "yyyy-MM-dd'T'HH:mm:s.ZZZZZZ"]
}
}

output {
  stdout { codec => rubydebug }
  elasticsearch { 
    # Your node IP addresses from the Instaclustr Console 
    hosts => ["http://172.18.5.95:9200"] 
     
    # The Logstash Username and Password created Earlier 
    user => "fil_team" 
    password => "fil-savarkaran-b5" 

    # Path to your Cluster Certificate .pem downloaded earlier 
    
    # The name of the Index 
    index => "fil-log"  
  }
}


