# Generated by Django 3.2 on 2022-07-26 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('generating', models.BooleanField(default=True)),
                ('sending', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('generator', models.GenericIPAddressField(protocol='IPv4')),
                ('insert_time', models.DateField(default=django.utils.timezone.now)),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khortum.payload')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khortum.source')),
            ],
        ),
    ]
