# Generated by Django 3.2 on 2022-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('khortum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
