# Generated by Django 3.2 on 2022-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('khortum', '0002_ip_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='signature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
