# Generated by Django 3.2 on 2022-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('khortum', '0003_ip_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='sending',
        ),
        migrations.AddField(
            model_name='payload',
            name='sending_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payload',
            name='sending_temp',
            field=models.BooleanField(default=False),
        ),
    ]
