# Generated by Django 3.2 on 2022-11-15 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('khortum', '0004_auto_20220921_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='type',
            field=models.CharField(default='manual-signature', max_length=64),
        ),
        migrations.AlterField(
            model_name='ip',
            name='insert_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
