# Generated by Django 3.2 on 2023-12-16 11:45

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('khortum', '0005_auto_20221115_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='attack_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='check',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('checking', 'checking'), ('blocked', 'blocked')], default='checking', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='update_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='update_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='appid_block_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[27459], null=True, size=None),
        ),
        migrations.AddField(
            model_name='payload',
            name='asn_block_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0], null=True, size=None),
        ),
        migrations.AddField(
            model_name='payload',
            name='detection_block_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, default=['27459p'], null=True, size=None),
        ),
        migrations.AddField(
            model_name='payload',
            name='dns_block_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=['anydns'], null=True, size=None),
        ),
        migrations.AddField(
            model_name='payload',
            name='min_traffic_1GB',
            field=models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AddField(
            model_name='payload',
            name='similarity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='similarity_asn_condition',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='ip',
            constraint=models.UniqueConstraint(fields=('ip', 'payload', 'source', 'generator', 'type'), name='unique_ip'),
        ),
    ]
