# Generated by Django 3.2 on 2024-01-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khortum', '0006_auto_20231216_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='type',
            field=models.CharField(default='manual-admin', max_length=64),
        ),
    ]
