# Generated by Django 3.2 on 2024-06-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khortum', '0007_alter_ip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='using_lower_timeframe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ip',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
