"""
Django settings for fil project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import json
import logging
import os
from pathlib import Path
from typing import Dict
import urllib3
urllib3.disable_warnings()

import logging.config

logging.getLogger("elasticsearch").setLevel(logging.WARNING)
logging.getLogger("kafka").setLevel(logging.WARNING)
logging.getLogger("parso").setLevel(logging.WARNING)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
DIR = Path(__file__).resolve().parent.parent
with open(os.path.join(DIR, '.env.json'), 'r') as f:
    config = json.load(fp=f)

with open(os.path.join(DIR, ".env.prod"), "r") as file:
    for line in file:
        # Ignore comments and empty lines
        if line.strip() and not line.strip().startswith("#"):
            key, value = line.strip().split("=", 1)
            os.environ[key] = value


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4c+u^f5#%8zd*t9_$q4l2)-%1ap!4exvqx#ea_=7w4ytk=ss7u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*'
]

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'khortum.apps.KhortumConfig',
    'aaj.apps.AajConfig',
    'hafeze.apps.HafezeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'drf_yasg'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fil.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fil.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DB_NAME = os.environ.get('DB_NAME', 'fildb')
DB_USER = os.environ.get('DB_USER', 'filuser')
DB_PASSWORD = os.environ.get('DB_PASSWORD', 'filpass')
DB_HOST = os.environ.get('DB_HOST', '172.30.113.242')
DB_PORT = os.environ.get('DB_PORT', '5432')

DB_NAME_SIZE = os.environ.get('DB_NAME_SIZE', 'fildb_daily')
DB_USER_SIZE = os.environ.get('DB_USER_SIZE', 'filuser')
DB_PASSWORD_SIZE = os.environ.get('DB_PASSWORD_SIZE', 'filpass')
DB_HOST_SIZE = os.environ.get('DB_HOST_SIZE', 'localhost')
DB_PORT_SIZE = os.environ.get('DB_PORT_SIZE', '5432')
# ML ATTACK PARAMETERS
NUMBER_OF_TRIES_CLUSTERING = os.environ.get('NUMBER_OF_TRIES_CLUSTERING', '20')
INITIAL_CLUSTER = os.environ.get('INITIAL_CLUSTER', '20')
CLUSTER_STEP = os.environ.get('CLUSTER_STEP', '5')
MINIMUM_IP_NUMBER_PER_PAYLOAD = os.environ.get('MINIMUM_IP_NUMBER_PER_PAYLOAD', '40')
PREFERD_PAYLOAD_PERCENT = os.environ.get('PREFERD_PAYLOAD_PERCENT', '25')
PREFERD_OTHER_PAYLOAD_PERCENT = os.environ.get('PREFERD_OTHER_PAYLOAD_PERCENT', '3')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'OPTIONS': {
            'sslmode': 'disable',}
    },
 
}

PESTE_NAME = os.environ.get('PESTE_NAME', 'peste')
PESTE_USER = os.environ.get('PESTE_USER', 'pesteuser')
PESTE_PASSWORD = os.environ.get('PESTE_PASSWORD', '#pestePass')
PESTE_HOST = os.environ.get('PESTE_HOST', '172.30.113.242')

DATA_PATH = config["ADDRESS"]["DATA_ADDRESS"]
INPUT_DATA_PATH = config["ADDRESS"]["INPUT_DATA_ADDRESS"]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STATIC_ROOT = os.environ.get('STATIC_ROOT', 'staticfiles')

LOG_LEVEL = config.get("LOG_LEVEL", "INFO")

APP_INFO = {
    "host_name": 'elastic',
    "name": "Fil",
}

IS_LCT = os.environ.get('IS_LCT', 'False') == 'True'
IS_TEST = os.environ.get('IS_TEST', 'False') == 'True'
IS_LCT = os.environ.get('IS_LCT', 'False') == 'True'
KAFKA_HOST = os.environ.get('KAFKA_HOST', '172.30.112.31')
KAFKA_PORT = os.environ.get('KAFKA_PORT', '9092')
SERVER_NAME = os.environ.get('SERVER_NAME', 'fil_test')

class SimpleLogger(logging.Logger):
    def error(self, msg, *args, **kwargs):
        if IS_TEST:
            raise Exception(msg)
        return super(SimpleLogger, self).error(msg, *args, **kwargs)


logging.setLoggerClass(SimpleLogger)

from autoutils.color import Colors

LOGGING_CONFIG = None

log_handlers = {
        "console": {
            "class": "fil.log_handlers.CustomColorfulStreamHandler",
            "level": LOG_LEVEL,
            "file_depth": 4,
            "file_color": Colors.BRIGHT_BLUE_F,
            "show_thread_id": False
        }
}

if IS_LCT:
    log_handlers["kafka"] = {
                "class": "fil.log_handlers.KafkaHandler",
                "level": "DEBUG",
                "log_servers": [f"{KAFKA_HOST}:{KAFKA_PORT}"],
                "server_name": SERVER_NAME,
                "topic": "fil_daily_log",
            }

log_config = {
    "version": 1,
    "handlers": log_handlers,
    "loggers": {
        "": {
            "handlers": log_handlers.keys(),
            "level": "DEBUG",
        },
        "django.db.backends": {
            "level": "INFO",
        },
    },
}
logging.config.dictConfig(log_config)

ELASTIC = config['ELASTIC']
CLIK_HOUSE = config['CLIK_HOUSE']
REMEMBER_BATCH_SIZE = int(os.environ.get('REMEMBER_BATCH_SIZE', '1000'))
REMEMBER_NUMBER_OF_PROCESSOR = int(os.environ.get('REMEMBER_NUMBER_OF_PROCESSOR', '10'))
REMEMBER_FETCH_SIZE = int(os.environ.get('REMEMBER_FETCH_SIZE', '1000000'))
REMEMBER_SPLIT_SIZE = int(os.environ.get('DETECT_SPLIT_SIZE', '4'))
KHORTUM_SPIDER_SAMPLE_SIZE = int(os.environ.get('KHORTUM_SPIDER_SAMPLE_SIZE', '10'))
KHORTUM_TIME_INTERVAL = os.environ.get('KHORTUM_TIME_INTERVAL', '300 d')
KHORTUM_SOURCES = ('Spider', 'spider', 'fil_manual')
ATTACK_CORE_NUMBER = int(os.environ.get('ATTACK_CORE_NUMBER', '3'))
LABEL_CORE_NUMBER = int(os.environ.get('ATTACK_CORE_NUMBER', '3'))
ATTACK_SPLIT_SIZE = int(os.environ.get('ATTACK_SPLIT_SIZE', '5'))
DETECT_CORE_NUMBER = int(os.environ.get('DETECT_CORE_NUMBER', '16'))
DETECT_SPLIT_SIZE = int(os.environ.get('DETECT_SPLIT_SIZE', '4'))
# partitioning
PARTITIONING_NUMBER_OF_MIN_SAMPLE = int(os.environ.get('PARTITIONING_NUMBER_OF_MIN_SAMPLE', '2'))
PARTITIONING_INTERVAL_DAYS = int(os.environ.get('PARTITIONING_INTERVAL_DAYS', '20'))
PARTITIONING_IP_UPDATE_COUNTER = int(os.environ.get('PARTITIONING_IP_UPDATE_COUNTER', '100'))
PARTITIONING_EPSILON = float(os.environ.get('PARTITIONING_EPSILON', '0.3'))
PARTITIONING_PROCESSORS_NUMBER = int(os.environ.get('PARTITIONING_PROCESSORS_NUMBER', '14'))
PARTITIONING_SIMILARITY_MODEL = int(os.environ.get('PARTITIONING_SIMILARITY_MODEL', '11'))
PARTITIONING_MAXIMUM_IP_INSTANCES = int(os.environ.get('PARTITIONING_MAXIMUM_IP_INSTANCES', '5000'))
IS_HOURLY = os.environ.get('IS_HOURLY', 'False') == 'True'  
IS_PRODUCTION = os.environ.get('IS_PRODUCTION', 'False') == 'True'  
REDIS_HOST = os.environ.get('REDIS_HOST', '172.30.113.242')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_IP_DAILY_DB = config["ADDRESS"]["REDIS_IP_DAILY_DB"]
REDIS_IP_HOURLY_DB = config["ADDRESS"]["REDIS_IP_HOURLY_DB"]
REDIS_IP_5MIN_DB = config["ADDRESS"]["REDIS_IP_5MIN_DB"]
REDIS_DNS_DB = config["ADDRESS"]["REDIS_DNS_DB"]
REDIS_DOMAIN_DB = config["ADDRESS"]["REDIS_DOMAIN_DB"]
REDIS_TMP_DB = config["ADDRESS"]["REDIS_TMP_DB"]
SMS_LOG_ADDRESS = config["ADDRESS"]["DATA_ADDRESS"] + "fil_sms.txt"
MODELS_ADDRESS = config["ADDRESS"]["DATA_ADDRESS"] + "models/"
DATASET_ADDRESS = config["ADDRESS"]["DATA_ADDRESS"] + "dataset"
DATASET_RAW_FILES = config["ADDRESS"]["DATA_ADDRESS"] + "raw/"
KAFKA_CONFIG = config["KAFKA"]
VERSION = os.environ.get('VERSION','0.13.0')
MLFLOW_HOST = os.environ.get('MLFLOW_HOST', '172.30.113.242')
FIL_DAILY_HOST = os.environ.get('FIL_DAILY_HOST','')
FIL_HOURLY_HOST = os.environ.get('FIL_HOURLY_HOST','')
AIRFLOW_HOST = os.environ.get('AIRFLOW_HOST', '172.18.5.107')
PRODUCTION_SERVER=os.environ.get('PRODUCTION_SERVER', '')
os.environ['MLFLOW_TRACKING_INSECURE_TLS'] = 'true'
