# Generated by Django 3.2 on 2024-02-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khortum', '0007_alter_ip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('payload_check_result', models.BooleanField(blank=True, null=True)),
                ('signature_check_result', models.BooleanField(blank=True, null=True)),
                ('ml_check_result', models.BooleanField(blank=True, null=True)),
                ('insert_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=768, null=True)),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khortum.payload')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khortum.source')),
            ],
            options={
                'verbose_name': 'Result Check',
                'verbose_name_plural': 'Result Checks',
                'db_table': 'result_check',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='resultcheck',
            constraint=models.UniqueConstraint(fields=('ip', 'payload', 'source'), name='unique_ip_payload_source'),
        ),
    ]
