# Generated by Django 3.2 on 2024-05-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hafeze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.CharField(blank=True, max_length=326, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detection_source', models.CharField(default='other', max_length=12)),
                ('note', models.CharField(blank=True, max_length=768, null=True)),
            ],
            options={
                'verbose_name': 'Cluster Ref',
                'verbose_name_plural': 'Cluster Refs',
                'db_table': 'cluster_ref',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IpCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('asn', models.CharField(blank=True, max_length=68, null=True)),
                ('traffic', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ip Cluster',
                'verbose_name_plural': 'Ip Clusters',
                'db_table': 'ip_cluster',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IpDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip1', models.GenericIPAddressField(verbose_name='ip1')),
                ('ip2', models.GenericIPAddressField(verbose_name='ip2')),
                ('distance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ip Distance',
                'verbose_name_plural': 'Ip Distances',
                'db_table': 'ip_distances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='resultcheck',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='resultcheck',
            name='ml_check_result',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resultcheck',
            name='payload_check_result',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resultcheck',
            name='signature_check_result',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='ipdistance',
            constraint=models.UniqueConstraint(fields=('ip1', 'ip2'), name='unique_ip1_ip2'),
        ),
        migrations.AddField(
            model_name='ipcluster',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hafeze.clusterref'),
        ),
        migrations.AddField(
            model_name='clusterref',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hafeze.tag'),
        ),
        migrations.AddConstraint(
            model_name='ipcluster',
            constraint=models.UniqueConstraint(fields=('ip', 'cluster'), name='unique_ip_cluster'),
        ),
    ]
