# Generated by Django 3.2 on 2022-12-25 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import aaj.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('khortum', '0005_auto_20221115_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('insert_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('appdst', models.FloatField(default=1)),
                ('sizedst', models.FloatField(default=1)),
                ('portdst', models.FloatField(default=1)),
                ('domaindst', models.FloatField(default=1)),
                ('dnsdst', models.FloatField(default=1)),
                ('script', models.TextField(validators=[aaj.models.validate_code])),
                ('generating', models.BooleanField(default=True)),
                ('sending_temp', models.BooleanField(default=False)),
                ('sending_main', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aaj.author')),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='khortum.payload')),
            ],
        ),
    ]
