# Generated by Django 3.2 on 2022-08-09 09:32

import django.utils.timezone
from django.db import migrations, models

import aaj.models


class Migration(migrations.Migration):
    dependencies = [
        ('aaj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='appdst',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='signature',
            name='dnsdst',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='signature',
            name='domaindst',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='signature',
            name='insert_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='signature',
            name='portdst',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='signature',
            name='script',
            field=models.TextField(validators=[aaj.models.validate_code]),
        ),
        migrations.AlterField(
            model_name='signature',
            name='sizedst',
            field=models.FloatField(default=1),
        ),
    ]
