# Generated by Django 3.2 on 2022-11-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aaj', '0002_auto_20220809_0932'),
    ]

    operations = [] # wrong migration for aaj signature.
