# Generated by Django 3.2 on 2023-05-03 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aaj', '0003_auto_20221126_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='needs_input',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=128)),
                ('generating', models.BooleanField(default=True)),
                ('sending_temp', models.BooleanField(default=False)),
                ('sending_main', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
