# Generated by Django 3.2 on 2024-05-05 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('khortum', '0007_alter_ip_type'),
        ('aaj', '0004_auto_20230503_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.CharField(max_length=256, null=True)),
                ('acronym', models.CharField(max_length=64)),
                ('insert_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('generating', models.BooleanField(default=True)),
                ('sending_temp', models.BooleanField(default=False)),
                ('sending_main', models.BooleanField(default=False)),
                ('config', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aaj.author')),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='khortum.payload')),
            ],
            options={
                'verbose_name': 'Intelligent Model',
                'verbose_name_plural': 'Intelligent Models',
                'db_table': 'intelligent_model',
                'ordering': ['-update_time'],
            },
        ),
    ]
